### PR TITLE
 Interactive list

### PR DESCRIPTION
**Pull request by Gegardus**
In this third part of the project, was added functionality to mark task completion by selecting the corresponding checkbox (or undo it by unchecking the checkbox). Also was Implemented a function for the "Clear all completed" button.

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @Gegardus 

Good job working on the project so far! 
✔️ There are no linter errors
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] According to the requirements, when I check the box it is supposed to change the completed property to true, and when I uncheck it the completed property is supposed to change to false As demonstrated in the image, that is not the case. When I check the box, the property is not changed and preserved in the localStorage. Kindly fix this.
Screenshot 2022-01-20 at 16 04 03

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Gegardus** [comment]
Hello, @Ghiftee I really don't understand how the checked status on your image is false. In my browser, everything works correctly. Here are screenshots. So I don't know what should be fixed.

This is checked:
Checked-true

And this is unchecked:
Unchecked-false

**Review by t-yanick — APPROVED** [review]
Hi @Gegardus, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gegardus** [comment]
Thank you.

**Pull request merged**
